# Generated by Django 4.1.3 on 2022-12-10 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("a89078c5-6840-41cd-a95f-c8c1e620bd44"),
                editable=False,
                verbose_name="Código",
            ),
        ),
    ]
