# Generated by Django 4.1.3 on 2022-12-04 17:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_parking_client_parking_code_parking_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="vehicle",
            field=models.CharField(
                choices=[
                    ("car", "Carro"),
                    ("motorcycle", "Moto"),
                    ("truck", "Caminhão"),
                ],
                default=datetime.datetime(2022, 12, 4, 17, 19, 43, 561514),
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("c8a446c8-2001-4385-9684-dd1fb09b7daa"),
                editable=False,
            ),
        ),
    ]
