# Generated by Django 4.1.3 on 2022-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_parking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="date_output",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parking",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
