# Generated by Django 4.1.3 on 2022-12-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_parking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default="X5TNP1I3", editable=False, verbose_name="Código"
            ),
        ),
    ]
