# Generated by Django 4.1.3 on 2022-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_parking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.CharField(
                default="UNVA5KMY", editable=False, max_length=8, verbose_name="Código"
            ),
        ),
    ]
