# Generated by Django 4.1.3 on 2022-12-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_parking_date_output_alter_parking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="date_input",
            field=models.DateTimeField(),
        ),
    ]
