# Generated by Django 4.1.3 on 2022-12-05 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_parking_code_alter_parking_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("47648dcb-eb93-4536-9bd7-2ff984182830"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="parking",
            name="date_output",
            field=models.DateTimeField(null=True),
        ),
    ]
