# Generated by Django 4.1.3 on 2022-12-05 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_parking_code_alter_parking_date_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("a3681d6d-271b-4264-af36-d5c66811b04b"),
                editable=False,
            ),
        ),
    ]
