# Generated by Django 4.1.3 on 2022-12-05 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_parking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="client",
            field=models.CharField(max_length=255, verbose_name="Cliente"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("93f5159c-ec73-4c3e-92d8-27e39d43f0ff"),
                editable=False,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="parking",
            name="date_input",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data entrada"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="date_output",
            field=models.DateTimeField(null=True, verbose_name="Data saída"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="left",
            field=models.BooleanField(default=False, verbose_name="Saída"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Pago"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="plate",
            field=models.CharField(max_length=8, verbose_name="Placa"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="value",
            field=models.FloatField(default=0, verbose_name="Valor"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="vehicle",
            field=models.CharField(
                choices=[
                    ("Carro", "Carro"),
                    ("Moto", "Moto"),
                    ("Caminhão", "Caminhão"),
                ],
                max_length=10,
                verbose_name="Veículo",
            ),
        ),
    ]
