# Generated by Django 4.1.3 on 2022-12-05 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_parking_client_alter_parking_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("648a0700-7a2a-46c1-a936-a80ecd624010"),
                editable=False,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="parking",
            name="date_output",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data saída"
            ),
        ),
    ]
